#!/bin/bash

# This script is used to update the Bliss manifest file

echo "You are going to update the Bliss manifest file."
echo "During the update, the current AOSP work directory (aosptree/) will be updated."
echo "If you have any local changes, they will be lost."
echo "Do you want to continue? [y/N]"
read -r answer
if [[ ! $answer =~ ^[Yy]$ ]]
then
    echo "Aborting"
    exit 1
fi

echo Init repo tree using Bliss OS manifest
pushd ../aosptree
repo init -u https://github.com/BlissRoms-x86/manifest.git -b arcadia-x86 --git-lfs
repo sync -c --force-sync -j4
repo manifest -r -o ../manifests/bliss-static.xml
popd

# Add the warning line at the beginning of the manifest
sed -i '2i\\n<!-- Autogenerated. Please do not edit. Run update_bliss_manifest.sh to update. -->\n' bliss-static.xml

echo -e "\n\033[32m   Done   \033[0m"
